on:
  push:
    tags:
      - "v*.*.*"

# on:
#   push:
#     branches: [main]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Build macOS app
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: M1necraft.xcodeproj
          scheme: M1necraft
          destination: platform=macOS
          action: build
          configuration: Release
      - name: (debug) show filetree
        run: |
          brew install tree
          tree -a
          tree -a ~/Library/Developer/Xcode/DerivedData
      - name: Compress app bundle
        run: |
          mv ~/Library/Developer/Xcode/DerivedData/M1necraft-*/Build/Products/Release/M1necraft.app .
          zip -r -y M1necraft.app.zip M1necraft.app
      - name: Copy Sparkle distribution archive
        run: |
          cp -r ~/Library/Developer/Xcode/DerivedData/M1necraft-*/SourcePackages/artifacts/sparkle .
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: ${{ github.workspace }}/M1necraft.app.zip
          retention-days: 1
      - name: Upload Sparkle tools
        uses: actions/upload-artifact@v2
        with:
          name: sparkle_updater
          path: |
            ${{ github.workspace }}/sparkle/bin
          retention-days: 1
  release:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build_artifacts
          path: ${{ github.workspace }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/M1necraft.app.zip
          generate_release_notes: true
  update-appcast:
    needs: [build, release]
    runs-on: macos-latest
    env:
      APPCAST_WORKDIR: ${{ github.workspace }}/appcast
    steps:
      - uses: actions/checkout@v3
      - name: Create ${{ env.APPCAST_WORKDIR }} directory
        run: mkdir $APPCAST_WORKDIR
      - uses: actions/download-artifact@v2
        with:
          name: sparkle_updater
          path: ${{ env.APPCAST_WORKDIR }}/bin
      - name: Import Sparkle keys
        working-directory: ${{ env.APPCAST_WORKDIR }}
        env:
          SPARKLE_PRIVATE_KEY: ${{ secrets.SPARKLE_PRIVATE_KEY }}
          SPARKLE_PRIVATE_KEY_PASSWORD: ${{ secrets.SPARKLE_PRIVATE_KEY_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          KEYCHAIN_PATH: ${{ runner.temp }}/sparkle.keychain-db
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security default-keychain -s "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          
          # echo -n "$SPARKLE_PRIVATE_KEY" | ./bin/generate_keys -f /dev/stdin
          
          security import <(cat <<< "$SPARKLE_PRIVATE_KEY") -P "$SPARKLE_PRIVATE_KEY_PASSWORD" -A -t priv -k "$KEYCHAIN_PATH"
      - name: Generate Appcast
        working-directory: ${{ env.APPCAST_WORKDIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          ${{ github.workspace }}/scripts/update_appcast
      - name: Publish Appcast
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ${{ env.APPCAST_WORKDIR }}
  bump-homebrew-cask:
    runs-on: macos-latest
    steps:
      - name: Bump Homebrew cask
        run: |
          BUMP_VERSION="${GITHUB_REF_NAME//v}"
          brew tap raphtlw/tap
          brew bump-cask-pr raphtlw/tap/m1necraft --version="$BUMP_VERSION" || true
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
