on:
  push:
    tags:
      - "v*.*.*"

# on:
#   push:
#     branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build macOS app
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: M1necraft.xcodeproj
          scheme: M1necraft
          destination: platform=macOS
          action: build
          configuration: Release
      - name: (debug) show filetree
        run: brew install tree && tree -a && tree -a ~/Library/Developer/Xcode/DerivedData
      - name: Compress app bundle
        run: |
          mv ~/Library/Developer/Xcode/DerivedData/M1necraft-*/Build/Products/Release/M1necraft.app .
          zip -r -y M1necraft.app.zip M1necraft.app
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: ${{ github.workspace }}/M1necraft.app.zip
          retention-days: 1
  release:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build_artifacts
          path: ${{ github.workspace }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/M1necraft.app.zip
          generate_release_notes: true
  bump-homebrew-cask:
    runs-on: macos-latest
    steps:
      - name: Homebrew bump cask
        uses: macauley/action-homebrew-bump-cask@v1
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          tap: raphtlw/homebrew-tap
          cask: m1necraft
